"""add_organ_models_and_scan_type

Revision ID: 12e51fee2f4e
Revises: 2094309b85c2
Create Date: 2026-04-01 10:16:20.524963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e51fee2f4e'
down_revision: Union[str, Sequence[str], None] = '2094309b85c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Önce nullable olarak ekle
    op.add_column('analyses', sa.Column('scan_type', sa.String(), nullable=True))
    
    # Mevcut kayıtlara default değer ver
    op.execute("UPDATE analyses SET scan_type = 'brain' WHERE scan_type IS NULL")
    
    # Sonra NOT NULL yap
    op.alter_column('analyses', 'scan_type', nullable=False)
    
    # organ_models tablosu (autogenerate bunu eklemediyse manuel ekle)
    op.create_table('organ_models',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('model_path', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('uploaded_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organ_models_id'), 'organ_models', ['id'], unique=False)
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'scan_type')
    # ### end Alembic commands ###
