"""patient_id nullable

Revision ID: 2094309b85c2
Revises: a3f4e6d7c890
Create Date: 2026-03-26 09:54:31.094000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2094309b85c2'
down_revision: Union[str, Sequence[str], None] = 'a3f4e6d7c890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_users_profile'), 'users', ['profile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_profile'), table_name='users')
    op.alter_column('analyses', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
