"""add_rbac_tables_v2

Revision ID: 76dc35a5f3b5
Revises: cb3afe8ddc0a
Create Date: 2026-03-14 11:45:35.274243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dc35a5f3b5'
down_revision: Union[str, Sequence[str], None] = 'cb3afe8ddc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
