"""rename_bleeding_to_finding

Revision ID: 84cefe7af02f
Revises: 12e51fee2f4e
Create Date: 2026-04-03 11:17:41.457463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84cefe7af02f'
down_revision: Union[str, Sequence[str], None] = '12e51fee2f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # organ_models'i silme — kaldır o satırları

    # analyses tablosu
    op.add_column('analyses', sa.Column('has_finding', sa.Boolean(), nullable=True))
    op.add_column('analyses', sa.Column('finding_type', sa.String(), nullable=True))
    op.execute("UPDATE analyses SET has_finding = is_bleeding")
    op.alter_column('analyses', 'has_finding', nullable=False)
    op.drop_column('analyses', 'is_bleeding')
    op.drop_column('analyses', 'bleeding_type')

    # analysis_reviews tablosu
    op.add_column('analysis_reviews', sa.Column('has_finding', sa.Boolean(), nullable=True))
    op.add_column('analysis_reviews', sa.Column('finding_type', sa.String(), nullable=True))
    op.execute("UPDATE analysis_reviews SET has_finding = is_bleeding")
    op.alter_column('analysis_reviews', 'has_finding', nullable=False)
    op.drop_column('analysis_reviews', 'is_bleeding')
    op.drop_column('analysis_reviews', 'bleeding_type')
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reviews', sa.Column('bleeding_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('analysis_reviews', sa.Column('is_bleeding', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('analysis_reviews', 'finding_type')
    op.drop_column('analysis_reviews', 'has_finding')
    op.add_column('analyses', sa.Column('bleeding_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('analyses', sa.Column('is_bleeding', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('analyses', 'finding_type')
    op.drop_column('analyses', 'has_finding')
    op.create_table('organ_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('organ_models_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('organ_models_pkey'))
    )
    op.create_index(op.f('ix_organ_models_id'), 'organ_models', ['id'], unique=False)
    # ### end Alembic commands ###
